# Numpy

In [1]:
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [2]:
import numpy as np
arr=np.array(l)
print(arr)

[1 2 3 4 5]


In [3]:
n=np.random.randn(1,100,5)

In [7]:
o=np.random.randint(1,100,5)
print(o)

[ 3 78 50 68 55]


## Why Numpy over Python List

1. Faster Execution
2. Less Memory Consumption -- 
4. Support Rectorized Operation
5. Easy Mathematical Operation
     --Numpy Supports
       *Mean,Sum,Min,Max,Median,Standard Deviation,Matrix
   

## Numpy Provides ndarray

1. 1D array -- Single Dimensional
   --all elements should generally be same datatype

2. 2D array --all elements are generally strored in rows and columns
3. Multi Dimensional Array

In [14]:
a=[1,2,3]
b=[4,5,6]
l=[]

if len(a)==len(b):
    for i in range(len(a)):
        r=a[i]+b[i]
        l.append(r)
    print(l)
else:
    print("Cannot Add")


[5, 7, 9]


In [16]:
import numpy as np
c=np.array([1,2,3])
d=np.array([4,5,6])
print(c+d)

[5 7 9]


In [18]:
print(c-d)
print(c*d)
print(c**d)
print(c/d)
print(c//d)

[-3 -3 -3]
[ 4 10 18]
[  1  32 729]
[0.25 0.4  0.5 ]
[0 0 0]


In [19]:
import numpy as np
ondar=np.array([1,2,3,4,5])
twdar=np.array([[1,2,3],[4,5,6]])
thdar=np.array([[[1,2],
             [3,4],
             [5,6]]])
print(ondar)
print(twdar)
print(thdar)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]
  [5 6]]]


## ndarray Attributes

1. ***Shape*** -- it show no of row and colums
2.  ***ndim*** -- shows number of dimensions of the array
3.  ***size*** --total no of element
4.  ***dtype*** -- it shows datatype

In [21]:
print(thdar.shape)
print(thdar.ndim)
print(twdar.ndim)
print(twdar.size)
print(twdar.dtype)

(1, 3, 2)
3
2
6
int32


## Array Creation in Numpy

  * **np.array()** --it convert python list/tuple to the numpy array item
  * **np.zeros()** --create array filled with zero
  * **np.ones()** --create an array filled with one
  * **np.array()** -- work like python 

In [22]:
import numpy as np
e=np.array([1,2,3,4,5])
f=np.zeros(5)
print(e)
print(f)
g=np.zeros((2,2))
print(c)

[1 2 3 4 5]
[0. 0. 0. 0. 0.]
[1 2 3]


In [23]:
print(np.ones(3))

[1. 1. 1.]


In [24]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
print(np.arange(1000))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [26]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [27]:
print(np.linspace(0,20,5))

[ 0.  5. 10. 15. 20.]


In [28]:
print(np.random.rand(10))

[0.53401309 0.60816935 0.95049112 0.15294265 0.59362708 0.05818752
 0.43941513 0.34444871 0.92994108 0.12508872]


In [30]:
print(np.random.randint(1,100,50))

[37  7 10 17 54 19 78 93 26 85 36 62 43 44 70 55 35 72 33 77 55 15 55 34
 45 11 49 27 36 46 28 79 41 68 51 14 46 21 29 69 21 15  5 98 26 62 61 94
 19 66]


In [36]:
print(np.random.randn(10))

[-0.02884308  1.13463115  0.87356347 -1.99993716 -1.23760325  1.3279448
 -0.25396987  0.61334532 -0.13053822  0.82394115]


In [37]:
print(np.random.randn(10,5))

[[ 1.25407594e+00 -1.40914688e+00 -7.66414914e-01 -1.30140443e-01
  -6.81076101e-01]
 [ 1.06310367e+00 -3.26794264e-01  1.49080673e+00 -3.94502458e-01
  -2.59525507e+00]
 [-1.18835694e+00  2.95328735e-01 -2.22691831e-01  6.54622375e-01
   4.74861611e-01]
 [-8.95984842e-01  4.79706667e-01  1.98270427e+00 -8.80826804e-02
  -5.10675884e-01]
 [ 1.91010297e-01 -9.43627756e-02  1.11051065e+00  8.24926064e-01
   1.27886123e+00]
 [-2.42797110e-01  5.88372526e-01  2.84011868e-01  5.75561453e-01
  -5.78702353e-01]
 [ 2.90654073e-01 -6.36266264e-02 -1.33582929e+00  1.90335063e+00
  -7.64220663e-01]
 [-2.03074778e+00  1.07367684e+00 -2.80817292e-01 -8.96031624e-01
  -7.99957303e-01]
 [ 2.04779991e+00 -2.08237866e-01 -1.31195935e-03  1.88703664e-01
  -5.14727384e-01]
 [ 1.43030233e+00 -3.39372099e-01  1.00719742e+00 -2.43275143e+00
   1.21072862e-01]]


## Numpy Indexing and Slicing

In [39]:
import numpy as np
i=np.array([10,20,30,40,50])
print(i[2])

30


In [40]:
j=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(j[1][1])

5


In [41]:
#1d slicing
print(i[2:6])

[30 40 50]


In [42]:
print(i[:4])

[10 20 30 40]


In [43]:
print(i[::2])

[10 30 50]


In [50]:
#2d slicing
print(i[1])

20


In [51]:
print(j[:1])

[[1 2 3]]


In [52]:
print(j[:-1])

[[1 2 3]
 [4 5 6]]


In [53]:
print(i[::-2])

[50 30 10]


In [54]:
print(i[-1])

50


In [61]:
print(j[-1])

[7 8 9]


In [62]:
print(j[:,1])

[2 5 8]


## Boolean and Fancy Indexing

In [66]:
print(j[j>5])

[6 7 8 9]


In [67]:
print(j[j<50])

[1 2 3 4 5 6 7 8 9]


## Mathemetical Operation in Numpy
1. Element wise Operation
2. Broadcasting -- it allow numpy to perform operation between array of different shape.
3. Matrix Operation --

In [68]:
import numpy as np
k=np.array([1,2,3])
print(k+10)

[11 12 13]


In [69]:
l=np.array([[1,2,3],[4,5,6]])
print(l+10)
print(k+l)

[[11 12 13]
 [14 15 16]]
[[2 4 6]
 [5 7 9]]


In [75]:
m=np.array([[1,2],
           [3,4]])
n=np.array([[4,3],
           [2,1]])

print(m*n)

[[4 6]
 [6 4]]


In [76]:
print(np.dot(m,n))

[[ 8  5]
 [20 13]]


In [74]:
print(m@n)

[[ 8  5]
 [20 13]]


In [79]:
print(np.matmul(m,n))

[[ 8  5]
 [20 13]]


In [77]:
print(n.T)

[[4 2]
 [3 1]]


In [78]:
print(m.T)

[[1 3]
 [2 4]]


In [84]:
print(np.sqrt(m))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [85]:
print(np.abs(m))

[[1 2]
 [3 4]]


In [86]:
print(np.log(m))

[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [87]:
print(np.exp(m))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [88]:
print(np.max(m))

4


In [89]:
print(np.min(m))

1


In [90]:
o=np.array([1.234,5.674])
print(np.round(o,2))

[1.23 5.67]


In [91]:
print(np.floor(o))

[1. 5.]


In [92]:
print(np.ceil(o))

[2. 6.]


## Statistical Function

--Uses
* Data Analysis
* Find Average
* Spread of Data
* Find Relationship between Variables

1. **Mean()** -- Find the Average Values
2. **Median()** -- Finds the Middle Value after sorting the array
3. **std()** (standard deviation) --How far Data are spread from mean
   * Small std -- data close to mean
   * Large std -- data spread wide
  
4. **Correlation** -- 
   * Positive
   * Negative
   * No
  
5. **Percentile** --

In [106]:
# Statistical Function
import numpy as np
p=np.array([10,2,30,40,5])
print(np.mean(p))
print(np.median(p))
print(np.std(p))
print(np.max(p))
print(np.min(p))
print(np.percentile(p,100))
print(np.var(p))
print(np.argmin(p))

17.4
10.0
14.934523762075576
40
2
40.0
223.04000000000002
1


In [107]:
q=np.array([1,2,3,4,5])
r=np.array([10,8,6,4,2])
print(np.corrcoef(b,c))

[[1. 1.]
 [1. 1.]]


In [111]:
s=np.array([[1,3,4],
            [5,6,8]])
np.sum(s,axis=0)

array([ 6,  9, 12])

In [112]:
np.sum(s,axis=1)

array([ 8, 19])

## Task:
1. Create 2D NumPy array of student scores; compute class average, highest scorer, normalize scores to 0-1 range.
2. Given arr = np.array([10,20,30,40,50]), write NumPy expressions to get all elements > 25 and compute their sum.
3. Give an example where a (3,1) is added with (1,4) array - what is the output shape?


In [120]:
stud_marks=np.array([[84,92,71],
                     [57,87,86],
                     [74,85,54],
                     [85,94,75]])

In [121]:
tot_marks=np.array([np.sum(stud_marks,axis=1)])

In [122]:
print(tot_marks)

[[247 230 213 254]]


In [123]:
average=np.mean(tot_marks)

In [124]:
print(average)

236.0


In [127]:
highest_score=(np.max(tot_marks))
print(highest_score)

254


In [129]:
norm=(tot_marks-np.min(tot_marks))/(np.max(tot_marks)-np.min(tot_marks))

In [130]:
print(norm)

[[0.82926829 0.41463415 0.         1.        ]]


In [136]:
subwise_total=np.sum(stud_marks,axis=0)

In [137]:
print(subwise_total)

[300 358 286]


In [138]:
subwise_average=np.mean(stud_marks,axis=0)

In [139]:
print(subwise_average)

[75.  89.5 71.5]
